// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluent.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConfluentEnvironmentState extends com.pulumi.resources.ResourceArgs {

    public static final ConfluentEnvironmentState Empty = new ConfluentEnvironmentState();

    /**
     * The name of the environment
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the environment
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private ConfluentEnvironmentState() {}

    private ConfluentEnvironmentState(ConfluentEnvironmentState $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConfluentEnvironmentState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConfluentEnvironmentState $;

        public Builder() {
            $ = new ConfluentEnvironmentState();
        }

        public Builder(ConfluentEnvironmentState defaults) {
            $ = new ConfluentEnvironmentState(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the environment
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the environment
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public ConfluentEnvironmentState build() {
            return $;
        }
    }

}
