// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Confluent
{
    [ConfluentResourceType("confluent:index/apiKey:ApiKey")]
    public partial class ApiKey : Pulumi.CustomResource
    {
        [Output("clusterId")]
        public Output<string?> ClusterId { get; private set; } = null!;

        /// <summary>
        /// Description
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Environment ID
        /// </summary>
        [Output("environmentId")]
        public Output<string> EnvironmentId { get; private set; } = null!;

        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// Logical Cluster ID List to create API Key
        /// </summary>
        [Output("logicalClusters")]
        public Output<ImmutableArray<string>> LogicalClusters { get; private set; } = null!;

        [Output("secret")]
        public Output<string> Secret { get; private set; } = null!;

        /// <summary>
        /// User ID
        /// </summary>
        [Output("userId")]
        public Output<int?> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a ApiKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ApiKey(string name, ApiKeyArgs args, CustomResourceOptions? options = null)
            : base("confluent:index/apiKey:ApiKey", name, args ?? new ApiKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ApiKey(string name, Input<string> id, ApiKeyState? state = null, CustomResourceOptions? options = null)
            : base("confluent:index/apiKey:ApiKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ApiKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ApiKey Get(string name, Input<string> id, ApiKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new ApiKey(name, id, state, options);
        }
    }

    public sealed class ApiKeyArgs : Pulumi.ResourceArgs
    {
        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Environment ID
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        [Input("logicalClusters")]
        private InputList<string>? _logicalClusters;

        /// <summary>
        /// Logical Cluster ID List to create API Key
        /// </summary>
        public InputList<string> LogicalClusters
        {
            get => _logicalClusters ?? (_logicalClusters = new InputList<string>());
            set => _logicalClusters = value;
        }

        /// <summary>
        /// User ID
        /// </summary>
        [Input("userId")]
        public Input<int>? UserId { get; set; }

        public ApiKeyArgs()
        {
        }
    }

    public sealed class ApiKeyState : Pulumi.ResourceArgs
    {
        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Environment ID
        /// </summary>
        [Input("environmentId")]
        public Input<string>? EnvironmentId { get; set; }

        [Input("key")]
        public Input<string>? Key { get; set; }

        [Input("logicalClusters")]
        private InputList<string>? _logicalClusters;

        /// <summary>
        /// Logical Cluster ID List to create API Key
        /// </summary>
        public InputList<string> LogicalClusters
        {
            get => _logicalClusters ?? (_logicalClusters = new InputList<string>());
            set => _logicalClusters = value;
        }

        [Input("secret")]
        public Input<string>? Secret { get; set; }

        /// <summary>
        /// User ID
        /// </summary>
        [Input("userId")]
        public Input<int>? UserId { get; set; }

        public ApiKeyState()
        {
        }
    }
}
