// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Confluent
{
    [ConfluentResourceType("confluent:index/schemaRegistry:SchemaRegistry")]
    public partial class SchemaRegistry : Pulumi.CustomResource
    {
        [Output("endpoint")]
        public Output<string> Endpoint { get; private set; } = null!;

        /// <summary>
        /// Environment ID
        /// </summary>
        [Output("environmentId")]
        public Output<string> EnvironmentId { get; private set; } = null!;

        /// <summary>
        /// where
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// Cloud provider
        /// </summary>
        [Output("serviceProvider")]
        public Output<string> ServiceProvider { get; private set; } = null!;


        /// <summary>
        /// Create a SchemaRegistry resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SchemaRegistry(string name, SchemaRegistryArgs args, CustomResourceOptions? options = null)
            : base("confluent:index/schemaRegistry:SchemaRegistry", name, args ?? new SchemaRegistryArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SchemaRegistry(string name, Input<string> id, SchemaRegistryState? state = null, CustomResourceOptions? options = null)
            : base("confluent:index/schemaRegistry:SchemaRegistry", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SchemaRegistry resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SchemaRegistry Get(string name, Input<string> id, SchemaRegistryState? state = null, CustomResourceOptions? options = null)
        {
            return new SchemaRegistry(name, id, state, options);
        }
    }

    public sealed class SchemaRegistryArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Environment ID
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        /// <summary>
        /// where
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        /// <summary>
        /// Cloud provider
        /// </summary>
        [Input("serviceProvider", required: true)]
        public Input<string> ServiceProvider { get; set; } = null!;

        public SchemaRegistryArgs()
        {
        }
    }

    public sealed class SchemaRegistryState : Pulumi.ResourceArgs
    {
        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        /// <summary>
        /// Environment ID
        /// </summary>
        [Input("environmentId")]
        public Input<string>? EnvironmentId { get; set; }

        /// <summary>
        /// where
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// Cloud provider
        /// </summary>
        [Input("serviceProvider")]
        public Input<string>? ServiceProvider { get; set; }

        public SchemaRegistryState()
        {
        }
    }
}
