// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Confluent
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("confluent");
        public static string? Password { get; set; } = __config.Get("password");

        public static string? Username { get; set; } = __config.Get("username");

    }
}
