// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "confluent:password")
}
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "confluent:username")
}
