// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluent;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("confluent");
    public Optional<String> password() {
        return Codegen.stringProp("password").config(config).get();
    }
    public Optional<String> username() {
        return Codegen.stringProp("username").config(config).get();
    }
}
