// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluent;

import com.pulumi.confluent.ConnectorArgs;
import com.pulumi.confluent.Utilities;
import com.pulumi.confluent.inputs.ConnectorState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="confluent:index/connector:Connector")
public class Connector extends com.pulumi.resources.CustomResource {
    /**
     * ID of containing cluster, e.g. lkc-abc123
     * 
     */
    @Export(name="clusterId", type=String.class, parameters={})
    private Output<String> clusterId;

    /**
     * @return ID of containing cluster, e.g. lkc-abc123
     * 
     */
    public Output<String> clusterId() {
        return this.clusterId;
    }
    /**
     * Type-specific Configuration of connector. String keys and values
     * 
     */
    @Export(name="config", type=Map.class, parameters={String.class, Object.class})
    private Output<Map<String,Object>> config;

    /**
     * @return Type-specific Configuration of connector. String keys and values
     * 
     */
    public Output<Map<String,Object>> config() {
        return this.config;
    }
    /**
     * Sensitive part of connector configuration. String keys and values
     * 
     */
    @Export(name="configSensitive", type=Map.class, parameters={String.class, Object.class})
    private Output</* @Nullable */ Map<String,Object>> configSensitive;

    /**
     * @return Sensitive part of connector configuration. String keys and values
     * 
     */
    public Output<Optional<Map<String,Object>>> configSensitive() {
        return Codegen.optional(this.configSensitive);
    }
    /**
     * ID of containing environment, e.g. env-abc123
     * 
     */
    @Export(name="environmentId", type=String.class, parameters={})
    private Output<String> environmentId;

    /**
     * @return ID of containing environment, e.g. env-abc123
     * 
     */
    public Output<String> environmentId() {
        return this.environmentId;
    }
    /**
     * The name of the connector
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return The name of the connector
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Connector(String name) {
        this(name, ConnectorArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Connector(String name, ConnectorArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Connector(String name, ConnectorArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("confluent:index/connector:Connector", name, args == null ? ConnectorArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Connector(String name, Output<String> id, @Nullable ConnectorState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("confluent:index/connector:Connector", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Connector get(String name, Output<String> id, @Nullable ConnectorState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Connector(name, id, state, options);
    }
}
