// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ConfluentEnvironment extends pulumi.CustomResource {
    /**
     * Get an existing ConfluentEnvironment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConfluentEnvironmentState, opts?: pulumi.CustomResourceOptions): ConfluentEnvironment {
        return new ConfluentEnvironment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'confluent:index/confluentEnvironment:ConfluentEnvironment';

    /**
     * Returns true if the given object is an instance of ConfluentEnvironment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConfluentEnvironment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConfluentEnvironment.__pulumiType;
    }

    /**
     * The name of the environment
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a ConfluentEnvironment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ConfluentEnvironmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConfluentEnvironmentArgs | ConfluentEnvironmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConfluentEnvironmentState | undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as ConfluentEnvironmentArgs | undefined;
            resourceInputs["name"] = args ? args.name : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConfluentEnvironment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConfluentEnvironment resources.
 */
export interface ConfluentEnvironmentState {
    /**
     * The name of the environment
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ConfluentEnvironment resource.
 */
export interface ConfluentEnvironmentArgs {
    /**
     * The name of the environment
     */
    name?: pulumi.Input<string>;
}
