// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./apiKey";
export * from "./environment";
export * from "./kafkaCluster";
export * from "./provider";
export * from "./schemaRegistry";
export * from "./serviceAccount";

// Export sub-modules:
import * as config from "./config";

export {
    config,
};

// Import resources to register:
import { ApiKey } from "./apiKey";
import { Environment } from "./environment";
import { KafkaCluster } from "./kafkaCluster";
import { SchemaRegistry } from "./schemaRegistry";
import { ServiceAccount } from "./serviceAccount";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "confluent:index/apiKey:ApiKey":
                return new ApiKey(name, <any>undefined, { urn })
            case "confluent:index/environment:Environment":
                return new Environment(name, <any>undefined, { urn })
            case "confluent:index/kafkaCluster:KafkaCluster":
                return new KafkaCluster(name, <any>undefined, { urn })
            case "confluent:index/schemaRegistry:SchemaRegistry":
                return new SchemaRegistry(name, <any>undefined, { urn })
            case "confluent:index/serviceAccount:ServiceAccount":
                return new ServiceAccount(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("confluent", "index/apiKey", _module)
pulumi.runtime.registerResourceModule("confluent", "index/environment", _module)
pulumi.runtime.registerResourceModule("confluent", "index/kafkaCluster", _module)
pulumi.runtime.registerResourceModule("confluent", "index/schemaRegistry", _module)
pulumi.runtime.registerResourceModule("confluent", "index/serviceAccount", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("confluent", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:confluent") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
